#include<iostream>
#include<vector>
#include<stack>
#include<algorithm>
using namespace std;
int dp(int i,vector<pair<int,int> > &memo,vector<bool> &sign,vector<vector<int> > &arr)
{
	if(sign[i])
		return memo[i].first;
	for(int j=0;j<i;j++)
	{
		if(arr[j][0]<=arr[i][1]&&dp(j,memo,sign,arr)+arr[i][2]>memo[i].first)
		{	
			memo[i].first=dp(j,memo,sign,arr)+arr[i][2];
			memo[i].second=j;
		}
	}
	sign[i]=1;
	return memo[i].first;
}
int main()
{
	int n;
	cout<<endl<<"ENTER THE TOTAL NO OF JOBS  :  ";
	cin>>n;
	vector<vector<int> > arr(n,vector<int> (3));
	cout<<endl<<endl<<"ENTER THE JOB TIMINGS  :  ";
	for(int i=0;i<n;i++)
		cin>>arr[i][1]>>arr[i][0]>>arr[i][2];	
	sort(arr.begin(),arr.end());
	vector<pair<int,int> > memo(n);
	vector<bool> sign(n,0);
	for(int i=0;i<n;i++)
	{
		memo[i].first=arr[i][2];
		memo[i].second=i;
	}
	int mx=0,storei;
	for(int i=0;i<n;i++)
	{
		int a=dp(i,memo,sign,arr);
		if(a>mx)
		{
			mx=memo[i].first;
			storei=i;
		}
	}
	cout<<endl<<endl<<"MAXIMUM PROFIT EARNED IS  :  "<<mx;
	cout<<endl<<endl<<"MAXIMUM PROFIT IS GENERATED BY  :  ";
	stack<int> st;
	while(storei!=memo[storei].second)
	{
		st.push(storei);
		storei=memo[storei].second;
	}
	st.push(storei);
	while(!st.empty())
	{
		cout<<st.top();
		st.pop();
		if(st.size())
			cout<<"--->";
	}
	cout<<endl<<endl;
}
