#include<iostream>
#include<vector>
#include<stack>
#include<algorithm>
using namespace std;
int main()
{
	int n;
	cout<<endl<<"ENTER THE TOTAL NO OF JOBS  :  ";
	cin>>n;
	vector<vector<int> > arr(n,vector<int> (3));
	cout<<endl<<endl<<"ENTER THE JOB TIMINGS  :  ";
	for(int i=0;i<n;i++)
		cin>>arr[i][1]>>arr[i][0]>>arr[i][2];
	sort(arr.begin(),arr.end());
	vector<pair<int,int> > ans(n);
	for(int i=0;i<n;i++)
	{
		ans[i].first=arr[i][2];
		ans[i].second=i;
	}
	int mx=0,storei;
	for(int i=0;i<n;i++)
	{
		for(int j=0;j<i;j++)
		{
			if(arr[j][0]<=arr[i][1]&&ans[j].first+arr[i][2]>ans[i].first)
			{
				ans[i].first=ans[j].first+arr[i][2];
				ans[i].second=j;
			}
		}
		if(ans[i].first>mx)
		{
			mx=ans[i].first;
			storei=i;
		}
	}
	cout<<endl<<endl<<"MAXIMUM PROFIT EARNED IS  :  "<<mx;
	cout<<endl<<endl<<"MAXIMUM PROFIT IS GENERATED BY  :  ";
	stack<int> st;
	while(storei!=ans[storei].second)
	{
		st.push(storei);
		storei=ans[storei].second;
	}
	st.push(storei);
	while(!st.empty())
	{
		cout<<st.top();
		st.pop();
		if(st.size())
			cout<<"--->";
	}
	cout<<endl<<endl;
}
